package github.jhkoder.aiblog.config;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import javax.sql.DataSource;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Flyway 마이그레이션 DDL 검증 테스트.
 *
 * prod 배포 시 schema validation 오류를 사전 방지한다.
 * V3의 PostgreSQL 전용 구문(ALTER COLUMN ... TYPE) 때문에
 * 전체 마이그레이션 체인 대신 각 버전 DDL을 H2에서 직접 실행해 검증한다.
 */
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class FlywayMigrationTest {

    private JdbcTemplate jdbcTemplate;

    @BeforeAll
    void setUp() {
        DataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:v6-test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL",
                "sa", ""
        );
        jdbcTemplate = new JdbcTemplate(dataSource);

        // members, posts 테이블 선행 생성 (FK 제약 조건 충족)
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS members (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    github_id VARCHAR(255) NOT NULL,
                    username  VARCHAR(255) NOT NULL,
                    avatar_url VARCHAR(255),
                    created_at TIMESTAMP NOT NULL DEFAULT NOW()
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS posts (
                    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    member_id BIGINT NOT NULL,
                    title     VARCHAR(255) NOT NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT NOW()
                )
                """);

        // V7: post_tags id 컬럼 추가 검증용 — id 없이 먼저 생성 후 ALTER 적용
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS post_tags (
                    post_id BIGINT NOT NULL REFERENCES posts(id),
                    tag     VARCHAR(255) NOT NULL
                )
                """);
        jdbcTemplate.execute("ALTER TABLE post_tags ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");

        // V6 DDL 직접 실행
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS ai_evaluations (
                    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    post_id            BIGINT    NOT NULL,
                    member_id          BIGINT    NOT NULL,
                    evaluation_content TEXT      NOT NULL,
                    model              VARCHAR(255) NOT NULL,
                    duration_ms        BIGINT,
                    created_at         TIMESTAMP NOT NULL,
                    CONSTRAINT fk_ai_evaluations_post   FOREIGN KEY (post_id)   REFERENCES posts(id),
                    CONSTRAINT fk_ai_evaluations_member FOREIGN KEY (member_id) REFERENCES members(id)
                )
                """);
        jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS idx_ai_evaluations_post_id        ON ai_evaluations (post_id)");
        jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS idx_ai_evaluations_member_created ON ai_evaluations (member_id, created_at)");
    }

    @Test
    @DisplayName("V6: ai_evaluations 테이블이 생성된다 — prod 배포 블로커 방지")
    void v6_ai_evaluations_테이블이_존재한다() {
        assertTableExists("ai_evaluations");
    }

    @Test
    @DisplayName("V6: ai_evaluations의 필수 컬럼 7개가 모두 존재한다")
    void v6_ai_evaluations_컬럼이_모두_존재한다() {
        Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM information_schema.columns " +
                "WHERE LOWER(table_name) = 'ai_evaluations' " +
                "AND LOWER(column_name) IN " +
                "('id','post_id','member_id','evaluation_content','model','duration_ms','created_at')",
                Integer.class
        );
        assertThat(count).isEqualTo(7);
    }

    @Test
    @DisplayName("V6: ai_evaluations에 데이터 삽입 및 조회가 가능하다")
    void v6_ai_evaluations_crud가_동작한다() {
        jdbcTemplate.execute("""
                INSERT INTO members (github_id, username, created_at)
                VALUES ('test-user', 'tester', NOW())
                """);
        jdbcTemplate.execute("""
                INSERT INTO posts (member_id, title, created_at)
                VALUES (1, 'test post', NOW())
                """);
        jdbcTemplate.execute("""
                INSERT INTO ai_evaluations (post_id, member_id, evaluation_content, model, duration_ms, created_at)
                VALUES (1, 1, '평가 내용', 'claude-sonnet-4-6', 1500, NOW())
                """);

        Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM ai_evaluations", Integer.class);
        assertThat(count).isEqualTo(1);
    }

    @Test
    @DisplayName("V6: ai_evaluations의 post_id FK 제약이 동작한다")
    void v6_ai_evaluations_fk_제약이_동작한다() {
        org.junit.jupiter.api.Assertions.assertThrows(Exception.class, () ->
                jdbcTemplate.execute("""
                        INSERT INTO ai_evaluations (post_id, member_id, evaluation_content, model, created_at)
                        VALUES (9999, 9999, '내용', 'model', NOW())
                        """)
        );
    }

    @Test
    @DisplayName("V7: post_tags 테이블에 id 컬럼이 존재한다 — prod 배포 블로커 방지")
    void v7_post_tags_id_컬럼이_존재한다() {
        Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM information_schema.columns " +
                "WHERE LOWER(table_name) = 'post_tags' AND LOWER(column_name) = 'id'",
                Integer.class
        );
        assertThat(count)
                .withFailMessage("post_tags.id 컬럼이 없습니다. V7 마이그레이션을 확인하세요.")
                .isEqualTo(1);
    }

    private void assertTableExists(String tableName) {
        Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM information_schema.tables WHERE LOWER(table_name) = ?",
                Integer.class,
                tableName.toLowerCase()
        );
        assertThat(count)
                .withFailMessage("테이블 [%s]가 존재하지 않습니다.", tableName)
                .isEqualTo(1);
    }
}
