spring:
  datasource:
    url: ENC(lni+njS8UwF2hx23Q5ND0tgNppn5A4F4/f2hhHntH4byZD9UmSyd+IZPDN9nooMe7Mq9wItalxH9EbNgXmr8nFdV2gjPU/64kAaCtHWiWmMPPspmQAVr3w==)
    driver-class-name: org.postgresql.Driver
    username: ENC(7++l2EV5iQejJSkuCLWzPhOBjlRjTs7IgiEPwM1PkYxvUQr/9MMZ4g==)
    password: ENC(D5+BdZdmZSNz2PnnfVsHTXC4uJcL0f+pvHdpXQu+kZw=)
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ENC(BG9Th9fT/0QDupaA3zCeSPqKfZWJgY6xnniEb9/l9RU=)
            client-secret: ENC(rPPSRGUEfBOA6Lq15wK3Dxt+bMU0rpRjxZEjzjnGiWXV04Vl8SHVBc3qtNUpn4L4g6ajDW3/iJc=)
            scope: read:user,user:email

frontend:
  url: "https://git-ai-blog.kr"

ai:
  daily-limit: 20

logging:
  level:
    github.jhkoder.aiblog: INFO
