spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aiblog
    driver-class-name: org.postgresql.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ENC(f3VTAM4li0GP8nUUWxkmjbfQOdSjQru6+ixUC1hBu5E=)
            client-secret: ENC(SOIHonk8q8Uj4AjuX9/DMwGz3dAYXBU1QcsjGel/NPZPj+FRNd1Euc2lqv9LqhStNge+uNnTbwM=)
            scope: read:user,user:email
            redirect-uri: http://localhost:8080/login/oauth2/code/github

ai:
  daily-limit: 20
